MovieSheduler.Presentation/Controllers/SheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MovieSheduler.Application.Cinema;
using MovieSheduler.Application.Cinema.Dtos;
using MovieSheduler.Application.Movie;
using MovieSheduler.Application.Movie.Dtos;
using MovieSheduler.Application.SheduleRecord;
using MovieSheduler.Application.SheduleRecord.Dtos;
using MovieSheduler.Presentation.Models;
using MovieSheduler.Presentation.Core;
using MovieSheduler.Presentation.Core.Messager;
using MovieSheduler.Presentation.Core.ModelBinder;

namespace MovieSheduler.Presentation.Controllers
{
    public class SheduleController : Controller
    {
        private readonly ISheduleRecordService _sheduleRecordService;
        private readonly IMovieService _movieService;
        private readonly ICinemaService _cinemaService;
        private readonly INotifier _notifier;

        public SheduleController(ISheduleRecordService sheduleRecordService, IMovieService movieService, ICinemaService cinemaService,
            INotifier notifier)
        {
            _sheduleRecordService = sheduleRecordService;
            _movieService = movieService;
            _cinemaService = cinemaService;
            _notifier = notifier;
        }

        public async Task<ActionResult> Index([ModelBinder(typeof(DateModelBinder))] DateTime? date)
        {
            IReadOnlyCollection<DateTime> availableDates = await _sheduleRecordService.GetAvailableDates();

            DateTime selectedDate;
            //If have date from user input and it available
            if (date.HasValue && availableDates.Contains(date.Value))
            {
                selectedDate = date.Value;
            }
            else
            {
                selectedDate = await _sheduleRecordService.GetFirstAvailableDate() ?? DateTime.Now;
            }

            GetSheduleByDateOutput shedule = await _sheduleRecordService.GetShedule(selectedDate);

            var model = new SheduleListViewModel(selectedDate, shedule.SheduleRecords, availableDates);

            return View(model);
        }

        public async Task<ActionResult> Add()
        {
            GetAllMoviesOutput movies = await _movieService.GetAllMovies();
            GetAllCinemaOutput cinemas = await _cinemaService.GetAllCinema();

            var model = new AddSheduleRecordViewModel(movies.Movies, cinemas.Cinemas);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(AddSheduleRecord record)
        {
            if (ModelState.IsValid)
            {
                //if record have some identical seans
                if (record.SeansList.GroupBy(t => t).Any(tg => tg.Count() > 1))
                {
                    ModelState.AddModelError("time", "Нельзя выбирать несколько одинаковых сеансов");
                }
                if (ModelState.IsValid)
                {
                    var result = _sheduleRecordService.AddRecord(new AddRecordInput(record.MovieId, record.CinemaId, record.SeansList, record.Date));
                    if (result.IsValid)
                    {
                        _notifier.Success("Раписание успешно добавлено!");
                        return RedirectToAction("Index", new { date = record.Date.ToShortDateString() });
                    }
                    ModelState.AddErrorsFromValidationDictionary(result);
                }
                GetAllMoviesOutput movies = await _movieService.GetAllMovies();
                GetAllCinemaOutput cinemas = await _cinemaService.GetAllCinema();

                var model = new AddSheduleRecordViewModel(movies.Movies, cinemas.Cinemas, record);
                return View(model);
            }
            //if we are here then critical error rised
            _notifier.Error("При добавление произошла ошибка!");
            return RedirectToAction("Add");
        }

        public async Task<ActionResult> Edit(int cinemaId, int movieId, [ModelBinder(typeof(DateModelBinder))] DateTime date)
        {
            if (!await _sheduleRecordService.RecordExist(new RecordExistInput(movieId, cinemaId, date)))
            {
                return HttpNotFound();
            }

            var model = await GetEditModel(cinemaId, movieId, date);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditSheduleRecord editRecord)
        {
            if (ModelState.IsValid)
            {
                if (!await _sheduleRecordService.RecordExist(new RecordExistInput(editRecord.MovieId, editRecord.CinemaId, editRecord.Date)))
                {
                    return HttpNotFound();
                }

                //if record have some identical seans
                if (editRecord.SeansList.GroupBy(t => t).Any(tg => tg.Count() > 1))
                {
                    ModelState.AddModelError("time", "Нельзя выбирать несколько одинаковых сеансов");
                }

                if (ModelState.IsValid)
                {
                    var result =
                        await _sheduleRecordService.EditRecord(new EditRecordInput(editRecord.CinemaId, editRecord.MovieId, editRecord.Date, editRecord.SeansList));
                    if (result.IsValid)
                    {
                        _notifier.Success("Раписание успешно отредактировано!");
                        return RedirectToAction("Index", new { date = editRecord.Date.ToShortDateString() });
                    }
                    ModelState.AddErrorsFromValidationDictionary(result);
                }

                MovieDto movie = await _movieService.GetMovieById(editRecord.MovieId);
                CinemaDto cinema = await _cinemaService.GetCinemaById(editRecord.CinemaId);
                var model = new EditSheduleRecordViewModel(cinema, movie, editRecord.Date, editRecord.SeansList);
                return View(model);
            }
            //if we are here then critical error rised
            _notifier.Error("При редактирование произошла ошибка!");
            return RedirectToAction("Edit", new { editRecord.CinemaId, editRecord.MovieId, date = editRecord.Date.ToShortDateString() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int cinemaId, int movieId, [ModelBinder(typeof(DateModelBinder))] DateTime date)
        {
            if (!await _sheduleRecordService.RecordExist(new RecordExistInput(movieId, cinemaId, date)))
            {
                return HttpNotFound();
            }

            var result = await _sheduleRecordService.DeleteRecords(new DeleteRecordsInput(cinemaId, movieId, date));
            if (result.IsValid)
            {
                _notifier.Success("Раписание успешно удалено!");
                return RedirectToAction("Index", new { date = date.ToShortDateString() });
            }

            ModelState.AddErrorsFromValidationDictionary(result);
            var model = await GetEditModel(cinemaId, movieId, date);
            return View("Edit", model);
        }

        private async Task<EditSheduleRecordViewModel> GetEditModel(int cinemaId, int movieId, DateTime date)
        {
            MovieDto movie = await _movieService.GetMovieById(movieId);
            CinemaDto cinema = await _cinemaService.GetCinemaById(cinemaId);
            IReadOnlyCollection<TimeSpan> seansList = await _sheduleRecordService.GetSeansList(new GetSeansonsInput(movieId, cinemaId, date));

            var model = new EditSheduleRecordViewModel(cinema, movie, date, seansList);
            return model;
        }
    }
}

MovieSheduler.Presentation/Views/Shedule/Add.cshtml
@model MovieSheduler.Presentation.Models.AddSheduleRecordViewModel

@{
    ViewBag.Title = "Добавление раписания";
}

<h2>Добавление раписания</h2>

@using (Html.BeginForm("Add", "Shedule", FormMethod.Post, new { @class = "form-horizontal", role = "form", data_validate_hidden = true }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.CinemaId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.CinemaId, Model.Cinemas, "Не выбрано", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.MovieId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.MovieId, Model.Movies, "Не выбрано", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <div data-datepicker data-hidden-field="Date" data-date="@(Model.Date!=default(DateTime)?Model.Date.Day+"/"+Model.Date.Month+"/"+Model.Date.Year:"")"></div>
            <input data-val="true" data-val-required="Нужно выбрать дату" name="Date" id="Date" value="@(Model.Date!=default(DateTime)?Model.Date.ToString():"")" type="hidden">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SeansList, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            <div data-time-list-container class="timeListContainer">
                @if (Model.SeansList.Any())
                {
                    foreach (var time in Model.SeansList)
                    {
                        <div data-time-list-item>
                            <div class="input-group time-item">
                                <input type="text" class="form-control" value="@time.Hours.ToString("00"):@time.Minutes.ToString("00")"  name="SeansList">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-info" data-time-list-remove aria-label="Help">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div data-time-list-item>
                        <div class="input-group time-item">
                            <input type="text" class="form-control" name="SeansList">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-info" data-time-list-remove aria-label="Help">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="button" class="btn btn-primary" data-time-list-add>
                <span class="glyphicon glyphicon-plus add-btn" aria-hidden="true"></span> Добавить
            </button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Сохранить"/>
            <a href="@Url.Action("Index")"  class="btn btn-warning">Отмена</a>
        </div>
    </div>
}

MovieSheduler.Presentation/Views/Shedule/Edit.cshtml
@model MovieSheduler.Presentation.Models.EditSheduleRecordViewModel

@{
    ViewBag.Title = "Редактирование расписания";
}

<h2>Редактирование расписания</h2>

@using (Html.BeginForm("Edit", "Shedule", FormMethod.Post, new { @class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m=>m.CinemaId)
    @Html.HiddenFor(m=>m.MovieId)
    @Html.HiddenFor(m=>m.Date)
    <div class="form-group">
        @Html.LabelFor(m => m.CinemaName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input class="form-control" value="@Model.CinemaName" type="text" disabled>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.MovieName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input class="form-control" value="@Model.MovieName" type="text" disabled>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input class="form-control" value="@Model.Date.ToShortDateString()" type="text" disabled>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SeansList, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            <div data-time-list-container class="timeListContainer">
                @foreach (var time in Model.SeansList)
                {
                    <div data-time-list-item>
                        <div class="input-group time-item">
                            <input type="text" class="form-control" value="@time.Hours.ToString("00"):@time.Minutes.ToString("00")" name="SeansList">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-info" data-time-list-remove aria-label="Help">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="button" class="btn btn-primary" data-time-list-add>
                <span class="glyphicon glyphicon-plus add-btn" aria-hidden="true"></span> Добавить
            </button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Сохранить"/>
            <a href="@Url.Action("Index")" class="btn btn-warning">Отмена</a>
            <input type="button" data-shedule-record-delete class="btn btn-danger" value="Удалить" />
        </div>
    </div>
}

@using (Html.BeginForm("Delete", "Shedule", FormMethod.Post, new { data_shedule_record_delete_form = true }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.CinemaId)
    @Html.HiddenFor(m => m.MovieId)
    @Html.HiddenFor(m => m.Date)
}

MovieSheduler.Presentation/Views/Shedule/Index.cshtml
@model MovieSheduler.Presentation.Models.SheduleListViewModel

@{
    ViewBag.Title = "Расписание";
}

<h2>Расписание</h2>
@using (Html.BeginForm("Index", "Shedule", FormMethod.Get, new { @class = "inline" }))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <select class="form-control inline" id="Date" name="Date">
        @foreach (var dateListItem in Model.AvailableDates)
        {
            <option value="@dateListItem.Text" @(dateListItem.Selected ? "selected" : "")>@dateListItem.Text</option>
        }
    </select>
    <input type="submit" class="btn btn-default" value="Показать" />
}


<a class="btn btn-default" href="@Url.Action("Add")">Добавить</a>
<table class="table">
    <thead>
        <tr>
            <th>
                Кинотеатр
            </th>
            <th>
                Фильм
            </th>
            <th>
                Сеансы
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cinema in Model.Cinemas)
        {
            <tr class="success">
                <td>@cinema.Name</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            foreach (var movie in cinema.Movies)
            {
                <tr>
                    <td></td>
                    <td>@movie.Name</td>
                    <td>@String.Join(", ", movie.TimeList)</td>
                    <td>@Html.ActionLink("Редактировать", "Edit", new { cinemaId = cinema.Id, movieId = movie.Id, date = Model.Date.ToShortDateString() }) </td>
                </tr>
            }
        }
    </tbody>
</table>